set(AUTH_TOKEN "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")

execute_process(
  COMMAND sh "-c" "curl -fsSL -H 'Authorization: Bearer ${AUTH_TOKEN}' https://api.github.com/repos/danceaway-app/sqlite/releases/tags/${VERSION}"
  COMMAND sh "-c" "jq -r '.assets[].url'"
  OUTPUT_VARIABLE DOWNLOAD_URL
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

vcpkg_download_distfile(
  ARCHIVE
  URLS ${DOWNLOAD_URL}
  FILENAME "amalgamation.tar.gz"
  SHA512 8cc3af9d3bb1368c4ffb024972f160a04228aa3c56eb01af2cdd35ace5bec2e6f6b77c1dc9850234639248cc016962af0db5742c9063e4aa2ad7f367c4e528d7
  HEADERS
    "Authorization: Bearer ${AUTH_TOKEN}"
    "Accept: application/octet-stream"
)

vcpkg_extract_source_archive(
  SOURCE_PATH
  ARCHIVE "${ARCHIVE}"
  NO_REMOVE_ONE_LEVEL
)

if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
  set(SQLITE_API "__attribute__((visibility(\"default\")))")
else()
  set(SQLITE_API "")
endif()

set(SQLITE_OS_UNIX "1")

file(COPY "${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt" DESTINATION "${SOURCE_PATH}")

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
      SQLITE_ENABLE_ATOMIC_WRITE=ON
      SQLITE_ENABLE_BATCH_ATOMIC_WRITE=ON
      SQLITE_ENABLE_COLUMN_METADATA=ON
      SQLITE_ENABLE_BYTECODE_VTAB=ON
      SQLITE_ENABLE_DBPAGE_VTAB=ON
      SQLITE_ENABLE_DBSTAT_VTAB=ON
      SQLITE_ENABLE_FTS5=ON
      SQLITE_ENABLE_GEOPOLY=ON
      SQLITE_ENABLE_ICU=ON
      SQLITE_ENABLE_MATH_FUNCTIONS=ON
      SQLITE_ENABLE_MEMORY_MANAGEMENT=ON
      SQLITE_ENABLE_MEMSYS5=ON
      SQLITE_ENABLE_PREUPDATE_HOOK=ON
      SQLITE_ENABLE_RTREE=ON
      SQLITE_ENABLE_SESSION=ON
      SQLITE_ENABLE_SNAPSHOT=ON
      SQLITE_ENABLE_STAT4=ON
      SQLITE_ENABLE_STMTVTAB=ON
      SQLITE_ENABLE_UPDATE_DELETE_LIMIT=ON
      SQLITE_LIKE_DOESNT_MATCH_BLOBS=ON
      SQLITE_OMIT_DEPRECATED=ON
      SQLITE_OMIT_PROGRESS_CALLBACK=ON
      SQLITE_OMIT_SHARED_CACHE=ON
      SQLITE_DQS=0
      SQLITE_DEFAULT_CACHE_SIZE=10000
      SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=5242880
      SQLITE_DEFAULT_MMAP_SIZE=5242880
      SQLITE_DEFAULT_WAL_SYNCHRONOUS=1
      SQLITE_DEFAULT_SYNCHRONOUS=1
      SQLITE_MAX_EXPR_DEPTH=0
      SQLITE_MAX_MEMORY=104857600
      SQLITE_MAX_MMAP_SIZE=10485760
      SQLITE_THREADSAFE=1
      SQLITE_TEMP_STORE=2
    OPTIONS_DEBUG
      SQLITE3_SKIP_TOOLS=ON
    MAYBE_UNUSED_VARIABLES
      SQLITE_TEMP_STORE=2
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(
  PACKAGE_NAME danceaway-${PORT}
  CONFIG_PATH share/danceaway-${PORT}
)

file(WRITE "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright" "SQLite is in the Public Domain.\nhttp://www.sqlite.org/copyright.html\n")
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
